services:
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:6.15
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - ./pgadmin_data:/pgadmin/storage
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped
#    networks:
#      - postgres

  postgres:
    container_name: postgres_container
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
       - ./postgres_data:/data/postgres
    ports:
      - 5432:5432
    restart: unless-stopped
#    networks:
#      - postgres
  

#networks:
#  postgres:
#    driver: bridge
